name: py-turf
channels:
  - defaults
dependencies:
  - appdirs=1.4.3=pyh91ea838_0
  - attrs=19.3.0=py_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - click=7.1.1=py_0
  - intel-openmp=2019.4=233
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.0.15=py38h5e564d8_0
  - mkl_random=1.1.0=py38h6440ff4_0
  - more-itertools=8.2.0=py_0
  - mypy_extensions=0.4.3=py38_0
  - ncurses=6.2=h0a44026_0
  - numpy=1.18.1=py38h7241aed_0
  - numpy-base=1.18.1=py38h6575580_1
  - openssl=1.1.1e=h1de35cc_0
  - packaging=20.3=py_0
  - pathspec=0.7.0=py_0
  - pip=20.0.2=py38_1
  - pluggy=0.13.1=py38_0
  - py=1.8.1=py_0
  - pyparsing=2.4.6=py_0
  - pytest=5.4.1=py38_0
  - python=3.8.1=h359304d_1
  - readline=7.0=h1de35cc_5
  - regex=2020.2.20=py38h1de35cc_0
  - setuptools=46.0.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - toml=0.10.0=pyh91ea838_0
  - typed-ast=1.4.1=py38h1de35cc_0
  - typing_extensions=3.7.4.1=py38_0
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - coverage==5.0.4
    - pytest-cov==2.8.1
prefix: /Users/diogomatoschaves/.conda/envs/py-turf

